CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE Veiculo(
	idVeiculo INT PRIMARY KEY IDENTITY(1,1),
	placaVeiculo VARCHAR(7) NOT NULL
);
GO

CREATE TABLE Empresa(
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES Veiculo(idVeiculo),
	nomeEmpresa VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE Marca(
	idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE Modelo(
	idModelo INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES Veiculo(idVeiculo),
	idMarca SMALLINT FOREIGN KEY REFERENCES Marca(idMarca),
	nomeModelo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE Cliente(
	idCliente INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES Veiculo(idVeiculo),
	nomeCliente VARCHAR(20) NOT NULL,
	cpfCliente VARCHAR(1) NOT NULL UNIQUE
);
GO
