CREATE DATABASE CATALOGO; 
GO

USE CATALOGO;
GO

CREATE TABLE Genero(
	idGenero TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeGenero VARCHAR(30)
);
GO

CREATE TABLE Filme(
	idFilme SMALLINT PRIMARY KEY IDENTITY(1,1),
	idGenero TINYINT FOREIGN KEY REFERENCES GENERO(idGenero),
	tituloFilme VARCHAR(100)
);
GO